#!/usr/bin/with-contenv bash
# vim: set ft=bash:

if [[ -n "${IO_CLASS}" ]]; then
   IONICE="ionice -c ${IO_CLASS}"
fi

umask 022

exec \
	${IONICE} s6-setuidgid abc /app/nzbget/nzbget -s -c /config/nzbget.conf \
	-o OutputMode=log
